Capture legislature name with correct encoding
everypolitician-scrapers/kosovo-parldata pull request #2
Opened 2017-02-09 18:33 UTC by ondenman

The legislature name was being captured with an ecoding error:
'Periudha e parÃ« Legjislative'

It was noticed that the legislature name was available elsewhere
within the document with the correct encoding.

This is a step towards fixing: https://github.com/everypolitician/everypolitician-data/issues/25276

2017-02-10 21:21 UTC, tmtmtmtm requested changes
1. If you're going to say that this is part of fixing an issue, you should really have a checkbox on that issue relating to this, so we can tick it off as done.

2. A bug fix should really have a regression test. If you're not going to add one, you should really explain why. (Adding one here would likely be a disproportionate amount of work, so I'd be OK with it, but it's still good practice to explicitly say so in the PR)

2017-02-13 11:33 UTC, tmtmtmtm commented
@ondenman you still don't seem to have addressed point 2 from above. Saying "This change does not have an associated regression test" doesn't explain _why_.

2017-02-13 15:06 UTC, tmtmtmtm requested changes
Your use of the passive here makes it sound like you don't really know _why_ what you're doing works.

What you're doing largely only accidentally happens to work with the current data from the remote source — it's not only not guaranteed to keep working in future, it's almost certain that it will _stop_ working…

Can you see why?

2017-02-14 09:53 UTC, ondenman commented
…because I'm capturing the string from `<changes>`. If a chamber doesn't have that, it won't work.

2017-02-14 09:56 UTC, tmtmtmtm commented
yes, though it's more than that, in that if there are multiple changes this code won't do the right thing either.

2017-02-14 10:42 UTC, ondenman commented
Would [this](https://github.com/everypolitician-scrapers/kosovo-parldata/pull/3) be a better solution?

2017-02-14 10:45 UTC, tmtmtmtm commented
What is the actual problem here? I don't just mean the manifestation of it — I mean the root cause.

2017-02-14 11:34 UTC, ondenman commented
It's an encoding problem. The source has encoded the 'ë' character incorrectly.

2017-02-14 11:47 UTC, tmtmtmtm commented
If you're sure that it's a problem with the source, rather than just our handling of it, have you reported it to them?

2017-02-14 12:01 UTC, ondenman commented
Parldata? Do we have a contact?

2017-05-17 16:07 UTC, ondenman commented
No longer needed. The issue has been closed (https://github.com/everypolitician/everypolitician-data/issues/25276).

2017-05-17 16:07 UTC, closed without merging